name: Hardhat CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Hardhat Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install project dependencies
        run: npm install

      - name: Run Solidity linter
        run: npm run lint

      - name: Compile contracts
        run: npm run compile

      - name: Run tests
        run: npm run test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          REPORT_GAS: ${{ secrets.REPORT_GAS }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          INITIAL_SUPPLY: ${{ secrets.INITIAL_SUPPLY }}
          MAX_SUPPLY: ${{ secrets.MAX_SUPPLY }}
          AIRDROP_AMOUNT: ${{ secrets.AIRDROP_AMOUNT }}

      - name: Deploy to Mumbai
        run: npm run deploy:mumbai
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          INITIAL_SUPPLY: ${{ secrets.INITIAL_SUPPLY }}
          MAX_SUPPLY: ${{ secrets.MAX_SUPPLY }}
          AIRDROP_AMOUNT: ${{ secrets.AIRDROP_AMOUNT }}
